#!/usr/bin/python3

class CLASS():
	CURRENCY = "Currency"
	## "Stackable Currency"
	## "Delve Socketable Currency"
	## "Delve Stackable Socketable Currency"

	ALL_MAP_ITEMS = "Map" #pseudo class
	## "Maps"
	## "Map Fragments"
	## "Labyrinth Map Item"
	## "Misc Map Items"

	CARD = "Divination Card"
	INCUBATOR = "Incubator"
	WATCHSTONE = "Atlas Region Upgrade Item"
	# "Life Flasks"
	# "Mana Flasks"
	# "Hybrid Flasks"
	# "Amulets"
	# "Rings"
	# "Claws"
	# "Daggers"
	# "Wands"
	# "One Hand Swords"
	# "Thrusting One Hand Swords"
	# "One Hand Axes"
	# "One Hand Maces"
	# "Bows"
	# "Staves"
	# "Two Hand Swords"
	# "Two Hand Axes"
	# "Two Hand Maces"
	# "Active Skill Gems"
	# "Support Skill Gems"
	# "Quivers"
	# "Belts"
	# "Gloves"
	# "Boots"
	# "Body Armours"
	# "Helmets"
	# "Shields"
	# "Quest Items"
	# "Sceptres"
	# "Utility Flasks"
	# "Fishing Rods"
	# "Hideout Doodads"
	# "Microtransactions"
	# "Jewel"
	# "Labyrinth Item"
	# "Labyrinth Trinket"
	# "Leaguestones"
	# "Pantheon Soul"
	# "Piece"
	# "Abyss Jewel"
	# "Incursion Item"
	# "Shard"
	# "Shard Heart"
	# "Rune Daggers"
	# "Warstaves"
	# "Metamorph Sample"

class FILTER():
	HIDE        = "Hide"
	SHOW        = "Show"
	COMMENT     = "#"
	TEMP_EFFECT = "Temp"
	EQ          = "="
	LT          = "<"
	GT          = ">"
	LE          = "<="
	GE          = ">="

	class CONDITION():
		#            "AreaLevel"       # [Operator] <Value>
		ITEM_LVL   = "ItemLevel"       # [Operator] <Level>
		#            "DropLevel"       # [Operator] <Level>
		QUALITY    = "Quality"         # [Operator] <Quality>
		RARITY     = "Rarity"          # [Operator] <Rarity>
		CLASS      = "Class"           #            <Class>
		BASE_TYPE  = "BaseType"        #            <Type>
		PROPHECY   = "Prophecy"        #            <Type>
		LINKS      = "LinkedSockets"   # [Operator] <Links>
		#            "SocketGroup"     # [Operator] <GroupSyntax>
		#            "Sockets"         # [Operator] <GroupSyntax>
		#            "Height"          # [Operator] <Value>
		#            "Width"           # [Operator] <Value>
		#            "HasExplicitMod"  #            <Value>
		#            "AnyEnchantment"  #            <Boolean>
		#            "HasEnchantment"  #            <Value>
		STACK_SIZE = "StackSize"       # [Operator] <Value>
		GEM_LVL    = "GemLevel"        # [Operator] <Value>
		#            "Identified"      #            <Boolean>
		CORRUPTED  = "Corrupted"       #            <Boolean>
		#            "CorruptedMods"   # [Operator] <Value>
		#            "Mirrored"        #            <Boolean>
		#            "ElderItem"       #            <Boolean>
		#            "ShaperItem"      #            <Boolean>
		INFLUENCE  = "HasInfluence"    #            <Type>
		#            "FracturedItem"   #            <Boolean>
		#            "SynthesisedItem" #            <Boolean>
		#            "ShapedMap"       #            <Boolean>
		MAP_TIER   = "MapTier"         # [Operator] <Value>

	class ACTION():
		TEXT_COLOR       = "SetTextColor"             # <Red> <Green> <Blue> [Alpha]
		BACKGROUND_COLOR = "SetBackgroundColor"       # <Red> <Green> <Blue> [Alpha]
		BORDER_COLOR     = "SetBorderColor"           # <Red> <Green> <Blue> [Alpha]
		FONT_SIZE        = "SetFontSize"              # <FontSize>
		EFFECT           = "PlayEffect"               #        <Color>         [Temp]
		ICON             = "MinimapIcon"              # <Size> <Color> <Shape>
		#                  "PlayAlertSound"           # <Id> [Volume]
		#                  "PlayAlertSoundPositional" # <Id> [Volume]
		#                  "DisableDropSound"
		#                  "CustomAlertSound"         # <FileName | FileFullPath>
		CONTINUE         = "Continue"

class EFFECT():
	class COLOR():
		RED    = "Red"
		YELLOW = "Yellow"
		WHITE  = "White"
		BROWN  = "Brown"
		BLUE   = "Blue"
		GREEN  = "Green"

class ICON():
	class SIZE():
		SMALL  = 2
		MEDIUM = 1
		LARGE  = 0

	class COLOR():
		RED    = "Red"
		YELLOW = "Yellow"
		WHITE  = "White"
		BROWN  = "Brown"
		BLUE   = "Blue"
		GREEN  = "Green"

	class SHAPE():
		HEXAGON  = "Hexagon"
		TRIANGLE = "Triangle"
		DIAMOND  = "Diamond"
		STAR     = "Star"
		SQUARE   = "Square"
		CIRCLE   = "Circle"

class RARITY():
	UNIQUE = "Unique"
	RARE = "Rare"
	MAGIC = "Magic"
	NORMAL = "Normal"

class WATCHSTONE():
	COBALT = "Cobalt Watchstone"
	CRIMSON = "Crimson Watchstone"
	GOLDEN = "Golden Watchstone"
	VIRIDIAN = "Viridian Watchstone"
	IVORY = "Ivory Watchstone"

CURRENCY = [
	"Fine Delirium Orb",
	"Singular Delirium Orb",
	"Thaumaturge's Delirium Orb",
	"Blacksmith's Delirium Orb",
	"Armoursmith's Delirium Orb",
	"Cartographer's Delirium Orb",
	"Jeweller's Delirium Orb",
	"Abyssal Delirium Orb",
	"Decadent Delirium Orb",
	"Foreboding Delirium Orb",
	"Obscured Delirium Orb",
	"Whispering Delirium Orb",
	"Fragmented Delirium Orb",
	"Skittering Delirium Orb",
	"Fossilised Delirium Orb",
	"Portentous Delirium Orb",
	"Diviner's Delirium Orb",
	"Delirium Orb",
	"Primal Delirium Orb",
	"Imperial Delirium Orb",
	"Timeless Delirium Orb",
	"Blighted Delirium Orb",
	"Amorphous Delirium Orb",
	"Simulacrum Splinter",
	"Pristine Fossil",
	"Awakener's Orb",
	"Albino Rhoa Feather",
	"Armourer's Scrap",
	"Awakened Sextant",
	"Bestiary Orb",
	"Blacksmith's Whetstone",
	"Blessed Orb",
	"Blessing of Chayula",
	"Blessing of Esh",
	"Blessing of Tul",
	"Blessing of Uul-Netol",
	"Blessing of Xoph",
	"Cartographer's Chisel",
	"Chaos Orb",
	"Chromatic Orb",
	"Crusader's Exalted Orb",
	"Divine Orb",
	"Exalted Orb",
	"Gemcutter's Prism",
	"Glassblower's Bauble",
	"Hunter's Exalted Orb",
	"Jeweller's Orb",
	"Mirror of Kalandra",
	"Orb of Alchemy",
	"Orb of Alteration",
	"Orb of Annulment",
	"Orb of Augmentation",
	"Orb of Chance",
	"Orb of Fusing",
	"Orb of Regret",
	"Orb of Scouring",
	"Orb of Transmutation",
	"Portal Scroll",
	"Prime Sextant",
	"Redeemer's Exalted Orb",
	"Regal Orb",
	"Scroll of Wisdom",
	"Silver Coin",
	"Simple Sextant",
	"Stacked Deck",
	"Vaal Orb",
	"Warlord's Exalted Orb",
	"Alchemy Shard",
	"Alteration Shard",
	"Scroll Fragment",
	"Splinter of Chayula",
	"Splinter of Esh",
	"Splinter of Tul",
	"Splinter of Uul-Netol",
	"Splinter of Xoph",
	"Transmutation Shard",
	"Vial of Awakening",
	"Vial of Consequence",
	"Vial of Dominance",
	"Vial of Fate",
	"Vial of Sacrifice",
	"Vial of Summoning",
	"Vial of the Ghost",
	"Vial of the Ritual",
	"Vial of Transcendence",
	"Ancient Orb",
	"Ancient Shard",
	"Annulment Shard",
	"Binding Shard",
	"Chaos Shard",
	"Engineer's Orb",
	"Engineer's Shard",
	"Exalted Shard",
	"Harbinger's Orb",
	"Harbinger's Shard",
	"Horizon Shard",
	"Mirror Shard",
	"Orb of Binding",
	"Orb of Horizons",
	"Regal Shard",
	"Perandus Coin",
	"Aberrant Fossil",
	"Aetheric Fossil",
	"Bloodstained Fossil",
	"Bound Fossil",
	"Corroded Fossil",
	"Dense Fossil",
	"Enchanted Fossil",
	"Encrusted Fossil",
	"Faceted Fossil",
	"Fractured Fossil",
	"Frigid Fossil",
	"Gilded Fossil",
	"Glyphic Fossil",
	"Hollow Fossil",
	"Jagged Fossil",
	"Lucent Fossil",
	"Metallic Fossil",
	"Perfect Fossil",
	"Prismatic Fossil",
	"Sanctified Fossil",
	"Scorched Fossil",
	"Serrated Fossil",
	"Shuddering Fossil",
	"Tangled Fossil",
	"Potent Alchemical Resonator",
	"Potent Chaotic Resonator",
	"Powerful Alchemical Resonator",
	"Powerful Chaotic Resonator",
	"Prime Alchemical Resonator",
	"Prime Chaotic Resonator",
	"Primitive Alchemical Resonator",
	"Primitive Chaotic Resonator",
	"Amber Oil",
	"Azure Oil",
	"Black Oil",
	"Clear Oil",
	"Crimson Oil",
	"Golden Oil",
	"Opalescent Oil",
	"Sepia Oil",
	"Silver Oil",
	"Teal Oil",
	"Verdant Oil",
	"Violet Oil",
	"Abrasive Catalyst",
	"Fertile Catalyst",
	"Imbued Catalyst",
	"Intrinsic Catalyst",
	"Prismatic Catalyst",
	"Tempering Catalyst",
	"Turbulent Catalyst",
	"Whispering Essence of Hatred",
	"Whispering Essence of Woe",
	"Whispering Essence of Greed",
	"Whispering Essence of Contempt",
	"Muttering Essence of Hatred",
	"Muttering Essence of Woe",
	"Muttering Essence of Greed",
	"Muttering Essence of Contempt",
	"Muttering Essence of Sorrow",
	"Muttering Essence of Anger",
	"Muttering Essence of Torment",
	"Muttering Essence of Fear",
	"Weeping Essence of Hatred",
	"Weeping Essence of Woe",
	"Weeping Essence of Greed",
	"Weeping Essence of Contempt",
	"Weeping Essence of Sorrow",
	"Weeping Essence of Anger",
	"Weeping Essence of Torment",
	"Weeping Essence of Fear",
	"Weeping Essence of Suffering",
	"Weeping Essence of Rage",
	"Weeping Essence of Wrath",
	"Weeping Essence of Doubt",
	"Wailing Essence of Hatred",
	"Wailing Essence of Woe",
	"Wailing Essence of Greed",
	"Wailing Essence of Contempt",
	"Wailing Essence of Sorrow",
	"Wailing Essence of Anger",
	"Wailing Essence of Torment",
	"Wailing Essence of Fear",
	"Wailing Essence of Suffering",
	"Wailing Essence of Rage",
	"Wailing Essence of Wrath",
	"Wailing Essence of Doubt",
	"Wailing Essence of Anguish",
	"Wailing Essence of Loathing",
	"Wailing Essence of Spite",
	"Wailing Essence of Zeal",
	"Screaming Essence of Hatred",
	"Screaming Essence of Woe",
	"Screaming Essence of Greed",
	"Screaming Essence of Contempt",
	"Screaming Essence of Sorrow",
	"Screaming Essence of Anger",
	"Screaming Essence of Torment",
	"Screaming Essence of Fear",
	"Screaming Essence of Suffering",
	"Screaming Essence of Rage",
	"Screaming Essence of Wrath",
	"Screaming Essence of Doubt",
	"Screaming Essence of Anguish",
	"Screaming Essence of Loathing",
	"Screaming Essence of Spite",
	"Screaming Essence of Zeal",
	"Screaming Essence of Misery",
	"Screaming Essence of Dread",
	"Screaming Essence of Scorn",
	"Screaming Essence of Envy",
	"Shrieking Essence of Hatred",
	"Shrieking Essence of Woe",
	"Shrieking Essence of Greed",
	"Shrieking Essence of Contempt",
	"Shrieking Essence of Sorrow",
	"Shrieking Essence of Anger",
	"Shrieking Essence of Torment",
	"Shrieking Essence of Fear",
	"Shrieking Essence of Suffering",
	"Shrieking Essence of Rage",
	"Shrieking Essence of Wrath",
	"Shrieking Essence of Doubt",
	"Shrieking Essence of Anguish",
	"Shrieking Essence of Loathing",
	"Shrieking Essence of Spite",
	"Shrieking Essence of Zeal",
	"Shrieking Essence of Misery",
	"Shrieking Essence of Dread",
	"Shrieking Essence of Scorn",
	"Shrieking Essence of Envy",
	"Deafening Essence of Hatred",
	"Deafening Essence of Woe",
	"Deafening Essence of Greed",
	"Deafening Essence of Contempt",
	"Deafening Essence of Sorrow",
	"Deafening Essence of Anger",
	"Deafening Essence of Torment",
	"Deafening Essence of Fear",
	"Deafening Essence of Suffering",
	"Deafening Essence of Rage",
	"Deafening Essence of Wrath",
	"Deafening Essence of Doubt",
	"Deafening Essence of Anguish",
	"Deafening Essence of Loathing",
	"Deafening Essence of Spite",
	"Deafening Essence of Zeal",
	"Deafening Essence of Misery",
	"Deafening Essence of Dread",
	"Deafening Essence of Scorn",
	"Deafening Essence of Envy",
	"Essence of Hysteria",
	"Essence of Insanity",
	"Essence of Horror",
	"Essence of Delirium",
	"Remnant of Corruption",
	"Timeless Eternal Empire Splinter",
	"Timeless Karui Splinter",
	"Timeless Maraketh Splinter",
	"Timeless Templar Splinter",
	"Timeless Vaal Splinter"]

DISCONTINUED_CURRENCY = [
	"Eternal Orb",
	"Unshaping Orb",
	"Apprentice Cartographer's Seal",
	"Journeyman Cartographer's Seal",
	"Master Cartographer's Seal",
	"Simple Rope Net",
	"Reinforced Rope Net",
	"Strong Rope Net",
	"Simple Iron Net",
	"Reinforced Iron Net",
	"Strong Iron Net",
	"Simple Steel Net",
	"Reinforced Steel Net",
	"Strong Steel Net",
	"Thaumaturgical Net",
	"Necromancy Net"]

CARDS = [
	"Echoes of Love",
	"Glimmer of Hope",
	"A Dab of Ink",
	"A Mother's Parting Gift",
	"Abandoned Wealth",
	"Akil's Prophecy",
	"Alluring Bounty",
	"Alone in the Darkness",
	"Anarchy's Price",
	"Arrogance of the Vaal",
	"Assassin's Favour",
	"Atziri's Arsenal",
	"Audacity",
	"Azyran's Reward",
	"Baited Expectations",
	"Beauty Through Death",
	"Blessing of God",
	"Blind Venture",
	"Boon of Justice",
	"Boon of the First Ones",
	"Boundless Realms",
	"Bowyer's Dream",
	"Buried Treasure",
	"Burning Blood",
	"Call to the First Ones",
	"Cameria's Cut",
	"Cartographer's Delight",
	"Chaotic Disposition",
	"Coveted Possession",
	"Dark Dreams",
	"Dark Temptation",
	"Death",
	"Deathly Designs",
	"Demigod's Wager",
	"Destined to Crumble",
	"Dialla's Subjugation",
	"Divine Justice",
	"Doedre's Madness",
	"Earth Drinker",
	"Emperor of Purity",
	"Emperor's Luck",
	"Etched in Blood",
	"Forbidden Power",
	"Friendship",
	"Gemcutter's Promise",
	"Gift of the Gemling Queen",
	"Grave Knowledge",
	"Harmony of Souls",
	"Her Mask",
	"Heterochromia",
	"Hope",
	"House of Mirrors",
	"Hubris",
	"Humility",
	"Hunter's Resolve",
	"Hunter's Reward",
	"Immortal Resolve",
	"Imperial Legacy",
	"Jack in the Box",
	"Lantador's Lost Love",
	"Last Hope",
	"Left to Fate",
	"Light and Truth",
	"Lingering Remnants",
	"Lost Worlds",
	"Loyalty",
	"Lucky Connections",
	"Lucky Deck",
	"Lysah's Respite",
	"Mawr Blaidd",
	"Merciless Armament",
	"Might is Right",
	"Mitts",
	"Monochrome",
	"More is Never Enough",
	"No Traces",
	"Nook's Crown",
	"Perfection",
	"Pride Before the Fall",
	"Pride of the First Ones",
	"Prosperity",
	"Rain of Chaos",
	"Rain Tempter",
	"Rats",
	"Rebirth",
	"Remembrance",
	"Sambodhi's Vow",
	"Scholar of the Seas",
	"Seven Years Bad Luck",
	"Shard of Fate",
	"Squandered Prosperity",
	"Struck by Lightning",
	"Succor of the Sinless",
	"The Admirer",
	"The Aesthete",
	"The Archmage's Right Hand",
	"The Arena Champion",
	"The Army of Blood",
	"The Artist",
	"The Avenger",
	"The Bargain",
	"The Battle Born",
	"The Beast",
	"The Betrayal",
	"The Blazing Fire",
	"The Body",
	"The Bones",
	"The Breach",
	"The Brittle Emperor",
	"The Cacophony",
	"The Calling",
	"The Carrion Crow",
	"The Cartographer",
	"The Cataclysm",
	"The Catalyst",
	"The Celestial Justicar",
	"The Celestial Stone",
	"The Chains that Bind",
	"The Chosen",
	"The Coming Storm",
	"The Conduit",
	"The Craving",
	"The Cursed King",
	"The Damned",
	"The Dapper Prodigy",
	"The Dark Mage",
	"The Darkest Dream",
	"The Deal",
	"The Deceiver",
	"The Deep Ones",
	"The Demon",
	"The Demoness",
	"The Doctor",
	"The Doppelganger",
	"The Dragon",
	"The Dragon's Heart",
	"The Dreamer",
	"The Dreamland",
	"The Drunken Aristocrat",
	"The Encroaching Darkness",
	"The Endless Darkness",
	"The Endurance",
	"The Enlightened",
	"The Escape",
	"The Ethereal",
	"The Explorer",
	"The Eye of Terror",
	"The Eye of the Dragon",
	"The Fathomless Depths",
	"The Feast",
	"The Fiend",
	"The Fishmonger",
	"The Fletcher",
	"The Flora's Gift",
	"The Fool",
	"The Formless Sea",
	"The Forsaken",
	"The Fox",
	"The Gambler",
	"The Garish Power",
	"The Gemcutter",
	"The Gentleman",
	"The Gladiator",
	"The Golden Era",
	"The Hale Heart",
	"The Harvester",
	"The Hermit",
	"The Heroic Shot",
	"The Hoarder",
	"The Hunger",
	"The Immortal",
	"The Incantation",
	"The Innocent",
	"The Inoculated",
	"The Insatiable",
	"The Inventor",
	"The Iron Bard",
	"The Jester",
	"The Jeweller's Boon",
	"The Journey",
	"The King's Blade",
	"The King's Heart",
	"The Landing",
	"The Last One Standing",
	"The Lich",
	"The Life Thief",
	"The Lion",
	"The Lord in Black",
	"The Lord of Celebration",
	"The Lover",
	"The Lunaris Priestess",
	"The Mad King",
	"The Master",
	"The Master Artisan",
	"The Mayor",
	"The Mercenary",
	"The Messenger",
	"The Metalsmith's Gift",
	"The Mountain",
	"The Nurse",
	"The Oath",
	"The Obscured",
	"The Offering",
	"The Old Man",
	"The One With All",
	"The Opulent",
	"The Pack Leader",
	"The Pact",
	"The Penitent",
	"The Poet",
	"The Polymath",
	"The Porcupine",
	"The Price of Loyalty",
	"The Primordial",
	"The Professor",
	"The Puzzle",
	"The Queen",
	"The Rabid Rhoa",
	"The Realm",
	"The Risk",
	"The Rite of Elements",
	"The Road to Power",
	"The Ruthless Ceinture",
	"The Sacrifice",
	"The Saint's Treasure",
	"The Samurai's Eye",
	"The Scarred Meadow",
	"The Scavenger",
	"The Scholar",
	"The Seeker",
	"The Sephirot",
	"The Side Quest",
	"The Sigil",
	"The Siren",
	"The Skeleton",
	"The Soul",
	"The Spark and the Flame",
	"The Spoiled Prince",
	"The Standoff",
	"The Stormcaller",
	"The Summoner",
	"The Sun",
	"The Surgeon",
	"The Surveyor",
	"The Survivalist",
	"The Sword King's Salute",
	"The Thaumaturgist",
	"The Throne",
	"The Tower",
	"The Traitor",
	"The Trial",
	"The Twilight Moon",
	"The Twins",
	"The Tyrant",
	"The Undaunted",
	"The Undisputed",
	"The Union",
	"The Valkyrie",
	"The Valley of Steel Boxes",
	"The Vast",
	"The Visionary",
	"The Void",
	"The Warden",
	"The Warlord",
	"The Watcher",
	"The Web",
	"The Wilted Rose",
	"The Wind",
	"The Witch",
	"The Wolf",
	"The Wolf's Legacy",
	"The Wolf's Shadow",
	"The Wolven King's Bite",
	"The Wolverine",
	"The World Eater",
	"The Wrath",
	"The Wretched",
	"Thirst for Knowledge",
	"Three Faces in the Dark",
	"Three Voices",
	"Thunderous Skies",
	"Time-Lost Relic",
	"Tranquillity",
	"Treasure Hunter",
	"Turn the Other Cheek",
	"Underground Forest",
	"Vanity",
	"Vile Power",
	"Vinia's Token",
	"Void of the Elements",
	"Volatile Power",
	"Wealth and Power"]

DISCONTINUED_CARDS = [
	"Birth of the Three",
	"Dying Anguish",
	"Luck of the Vaal",
	"The Devastator",
	"The Price of Protection"]

STACK_SIZES = {
	"Fine Delirium Orb": 10,
	"Singular Delirium Orb": 10,
	"Thaumaturge's Delirium Orb": 10,
	"Blacksmith's Delirium Orb": 10,
	"Armoursmith's Delirium Orb": 10,
	"Cartographer's Delirium Orb": 10,
	"Jeweller's Delirium Orb": 10,
	"Abyssal Delirium Orb": 10,
	"Decadent Delirium Orb": 10,
	"Foreboding Delirium Orb": 10,
	"Obscured Delirium Orb": 10,
	"Whispering Delirium Orb": 10,
	"Fragmented Delirium Orb": 10,
	"Skittering Delirium Orb": 10,
	"Fossilised Delirium Orb": 10,
	"Portentous Delirium Orb": 10,
	"Diviner's Delirium Orb": 10,
	"Delirium Orb": 10,
	"Primal Delirium Orb": 10,
	"Imperial Delirium Orb": 10,
	"Timeless Delirium Orb": 10,
	"Blighted Delirium Orb": 10,
	"Amorphous Delirium Orb": 10,
	"Simulacrum Splinter": 100,
	"Pristine Fossil": 20,
	"Echoes of Love": 3,
	"Glimmer of Hope": 8,
	"Awakener's Orb": 10,
	"Albino Rhoa Feather": 10,
	"Armourer's Scrap": 40,
	"Awakened Sextant": 10,
	"Bestiary Orb": 10,
	"Blacksmith's Whetstone": 20,
	"Blessed Orb": 20,
	"Blessing of Chayula": 10,
	"Blessing of Esh": 10,
	"Blessing of Tul": 10,
	"Blessing of Uul-Netol": 10,
	"Blessing of Xoph": 10,
	"Cartographer's Chisel": 20,
	"Chaos Orb": 10,
	"Chromatic Orb": 20,
	"Crusader's Exalted Orb": 10,
	"Divine Orb": 10,
	"Exalted Orb": 10,
	"Gemcutter's Prism": 20,
	"Glassblower's Bauble": 20,
	"Hunter's Exalted Orb": 10,
	"Jeweller's Orb": 20,
	"Mirror of Kalandra": 10,
	"Orb of Alchemy": 10,
	"Orb of Alteration": 20,
	"Orb of Annulment": 20,
	"Orb of Augmentation": 30,
	"Orb of Chance": 20,
	"Orb of Fusing": 20,
	"Orb of Regret": 40,
	"Orb of Scouring": 30,
	"Orb of Transmutation": 40,
	"Portal Scroll": 40,
	"Prime Sextant": 10,
	"Redeemer's Exalted Orb": 10,
	"Regal Orb": 10,
	"Scroll of Wisdom": 40,
	"Silver Coin": 30,
	"Simple Sextant": 10,
	"Stacked Deck": 10,
	"Vaal Orb": 10,
	"Warlord's Exalted Orb": 10,
	"Alchemy Shard": 20,
	"Alteration Shard": 20,
	"Scroll Fragment": 5,
	"Splinter of Chayula": 100,
	"Splinter of Esh": 100,
	"Splinter of Tul": 100,
	"Splinter of Uul-Netol": 100,
	"Splinter of Xoph": 100,
	"Transmutation Shard": 20,
	"Vial of Awakening": 10,
	"Vial of Consequence": 10,
	"Vial of Dominance": 10,
	"Vial of Fate": 10,
	"Vial of Sacrifice": 10,
	"Vial of Summoning": 10,
	"Vial of the Ghost": 10,
	"Vial of the Ritual": 10,
	"Vial of Transcendence": 10,
	"Ancient Orb": 20,
	"Ancient Shard": 20,
	"Annulment Shard": 20,
	"Binding Shard": 20,
	"Chaos Shard": 20,
	"Engineer's Orb": 20,
	"Engineer's Shard": 20,
	"Exalted Shard": 20,
	"Harbinger's Orb": 20,
	"Harbinger's Shard": 20,
	"Horizon Shard": 20,
	"Mirror Shard": 20,
	"Orb of Binding": 20,
	"Orb of Horizons": 20,
	"Regal Shard": 20,
	"Perandus Coin": 1000,
	"Aberrant Fossil": 20,
	"Aetheric Fossil": 20,
	"Bloodstained Fossil": 20,
	"Bound Fossil": 20,
	"Corroded Fossil": 20,
	"Dense Fossil": 20,
	"Enchanted Fossil": 20,
	"Encrusted Fossil": 20,
	"Faceted Fossil": 20,
	"Fractured Fossil": 20,
	"Frigid Fossil": 20,
	"Gilded Fossil": 20,
	"Glyphic Fossil": 20,
	"Hollow Fossil": 20,
	"Jagged Fossil": 20,
	"Lucent Fossil": 20,
	"Metallic Fossil": 20,
	"Perfect Fossil": 20,
	"Prismatic Fossil": 20,
	"Sanctified Fossil": 20,
	"Scorched Fossil": 20,
	"Serrated Fossil": 20,
	"Shuddering Fossil": 20,
	"Tangled Fossil": 20,
	"Potent Alchemical Resonator": 10,
	"Potent Chaotic Resonator": 10,
	"Powerful Alchemical Resonator": 10,
	"Powerful Chaotic Resonator": 10,
	"Prime Alchemical Resonator": 10,
	"Prime Chaotic Resonator": 10,
	"Primitive Alchemical Resonator": 10,
	"Primitive Chaotic Resonator": 10,
	"Amber Oil": 10,
	"Azure Oil": 10,
	"Black Oil": 10,
	"Clear Oil": 10,
	"Crimson Oil": 10,
	"Golden Oil": 10,
	"Opalescent Oil": 10,
	"Sepia Oil": 10,
	"Silver Oil": 10,
	"Teal Oil": 10,
	"Verdant Oil": 10,
	"Violet Oil": 10,
	"Abrasive Catalyst": 10,
	"Fertile Catalyst": 10,
	"Imbued Catalyst": 10,
	"Intrinsic Catalyst": 10,
	"Prismatic Catalyst": 10,
	"Tempering Catalyst": 10,
	"Turbulent Catalyst": 10,
	"Whispering Essence of Hatred": 9,
	"Whispering Essence of Woe": 9,
	"Whispering Essence of Greed": 9,
	"Whispering Essence of Contempt": 9,
	"Muttering Essence of Hatred": 9,
	"Muttering Essence of Woe": 9,
	"Muttering Essence of Greed": 9,
	"Muttering Essence of Contempt": 9,
	"Muttering Essence of Sorrow": 9,
	"Muttering Essence of Anger": 9,
	"Muttering Essence of Torment": 9,
	"Muttering Essence of Fear": 9,
	"Weeping Essence of Hatred": 9,
	"Weeping Essence of Woe": 9,
	"Weeping Essence of Greed": 9,
	"Weeping Essence of Contempt": 9,
	"Weeping Essence of Sorrow": 9,
	"Weeping Essence of Anger": 9,
	"Weeping Essence of Torment": 9,
	"Weeping Essence of Fear": 9,
	"Weeping Essence of Suffering": 9,
	"Weeping Essence of Rage": 9,
	"Weeping Essence of Wrath": 9,
	"Weeping Essence of Envy": 9,
	"Wailing Essence of Hatred": 9,
	"Wailing Essence of Woe": 9,
	"Wailing Essence of Greed": 9,
	"Wailing Essence of Contempt": 9,
	"Wailing Essence of Sorrow": 9,
	"Wailing Essence of Anger": 9,
	"Wailing Essence of Torment": 9,
	"Wailing Essence of Fear": 9,
	"Wailing Essence of Suffering": 9,
	"Wailing Essence of Rage": 9,
	"Wailing Essence of Wrath": 9,
	"Wailing Essence of Doubt": 9,
	"Wailing Essence of Anguish": 9,
	"Wailing Essence of Loathing": 9,
	"Wailing Essence of Spite": 9,
	"Wailing Essence of Zeal": 9,
	"Screaming Essence of Hatred": 9,
	"Screaming Essence of Woe": 9,
	"Screaming Essence of Greed": 9,
	"Screaming Essence of Contempt": 9,
	"Screaming Essence of Sorrow": 9,
	"Screaming Essence of Anger": 9,
	"Screaming Essence of Torment": 9,
	"Screaming Essence of Fear": 9,
	"Screaming Essence of Suffering": 9,
	"Screaming Essence of Rage": 9,
	"Screaming Essence of Wrath": 9,
	"Screaming Essence of Doubt": 9,
	"Screaming Essence of Anguish": 9,
	"Screaming Essence of Loathing": 9,
	"Screaming Essence of Spite": 9,
	"Screaming Essence of Zeal": 9,
	"Screaming Essence of Misery": 9,
	"Screaming Essence of Dread": 9,
	"Screaming Essence of Scorn": 9,
	"Screaming Essence of Envy": 9,
	"Shrieking Essence of Hatred": 9,
	"Shrieking Essence of Woe": 9,
	"Shrieking Essence of Greed": 9,
	"Shrieking Essence of Contempt": 9,
	"Shrieking Essence of Sorrow": 9,
	"Shrieking Essence of Anger": 9,
	"Shrieking Essence of Torment": 9,
	"Shrieking Essence of Fear": 9,
	"Shrieking Essence of Suffering": 9,
	"Shrieking Essence of Rage": 9,
	"Shrieking Essence of Wrath": 9,
	"Shrieking Essence of Doubt": 9,
	"Shrieking Essence of Anguish": 9,
	"Shrieking Essence of Loathing": 9,
	"Shrieking Essence of Spite": 9,
	"Shrieking Essence of Zeal": 9,
	"Shrieking Essence of Misery": 9,
	"Shrieking Essence of Dread": 9,
	"Shrieking Essence of Scorn": 9,
	"Shrieking Essence of Envy": 9,
	"Deafening Essence of Hatred": 9,
	"Deafening Essence of Woe": 9,
	"Deafening Essence of Greed": 9,
	"Deafening Essence of Contempt": 9,
	"Deafening Essence of Sorrow": 9,
	"Deafening Essence of Anger": 9,
	"Deafening Essence of Torment": 9,
	"Deafening Essence of Fear": 9,
	"Deafening Essence of Suffering": 9,
	"Deafening Essence of Rage": 9,
	"Deafening Essence of Wrath": 9,
	"Deafening Essence of Doubt": 9,
	"Deafening Essence of Anguish": 9,
	"Deafening Essence of Loathing": 9,
	"Deafening Essence of Spite": 9,
	"Deafening Essence of Zeal": 9,
	"Deafening Essence of Misery": 9,
	"Deafening Essence of Dread": 9,
	"Deafening Essence of Scorn": 9,
	"Deafening Essence of Envy": 9,
	"Essence of Hysteria": 9,
	"Essence of Insanity": 9,
	"Essence of Horror": 9,
	"Essence of Delirium": 9,
	"Remnant of Corruption": 9,
	"Eternal Orb": 10,
	"Unshaping Orb": 10,
	"Apprentice Cartographer's Seal": 10,
	"Journeyman Cartographer's Seal": 10,
	"Master Cartographer's Seal": 10,
	"Simple Rope Net": 100,
	"Reinforced Rope Net": 100,
	"Strong Rope Net": 100,
	"Simple Iron Net": 100,
	"Reinforced Iron Net": 100,
	"Strong Iron Net": 100,
	"Simple Steel Net": 100,
	"Reinforced Steel Net": 100,
	"Strong Steel Net": 100,
	"Thaumaturgical Net": 100,
	"Necromancy Net": 100,	"A Dab of Ink": 9,
	"A Mother's Parting Gift": 6,
	"Abandoned Wealth": 5,
	"Akil's Prophecy": 3,
	"Alluring Bounty": 7,
	"Alone in the Darkness": 5,
	"Anarchy's Price": 13,
	"Arrogance of the Vaal": 8,
	"Assassin's Favour": 9,
	"Atziri's Arsenal": 4,
	"Audacity": 5,
	"Azyran's Reward": 9,
	"Baited Expectations": 8,
	"Beauty Through Death": 5,
	"Blessing of God": 3,
	"Blind Venture": 7,
	"Boon of Justice": 6,
	"Boon of the First Ones": 6,
	"Boundless Realms": 4,
	"Bowyer's Dream": 6,
	"Buried Treasure": 3,
	"Burning Blood": 6,
	"Call to the First Ones": 5,
	"Cameria's Cut": 2,
	"Cartographer's Delight": 3,
	"Chaotic Disposition": 1,
	"Coveted Possession": 9,
	"Dark Dreams": 4,
	"Dark Temptation": 5,
	"Death": 4,
	"Deathly Designs": 7,
	"Demigod's Wager": 7,
	"Destined to Crumble": 5,
	"Dialla's Subjugation": 7,
	"Divine Justice": 1,
	"Doedre's Madness": 9,
	"Earth Drinker": 5,
	"Emperor of Purity": 7,
	"Emperor's Luck": 5,
	"Etched in Blood": 9,
	"Forbidden Power": 4,
	"Friendship": 3,
	"Gemcutter's Promise": 3,
	"Gift of the Gemling Queen": 9,
	"Grave Knowledge": 6,
	"Harmony of Souls": 9,
	"Her Mask": 4,
	"Heterochromia": 2,
	"Hope": 5,
	"House of Mirrors": 9,
	"Hubris": 5,
	"Humility": 9,
	"Hunter's Resolve": 8,
	"Hunter's Reward": 3,
	"Immortal Resolve": 6,
	"Imperial Legacy": 22,
	"Jack in the Box": 4,
	"Lantador's Lost Love": 7,
	"Last Hope": 3,
	"Left to Fate": 4,
	"Light and Truth": 2,
	"Lingering Remnants": 16,
	"Lost Worlds": 8,
	"Loyalty": 5,
	"Lucky Connections": 7,
	"Lucky Deck": 9,
	"Lysah's Respite": 6,
	"Mawr Blaidd": 16,
	"Merciless Armament": 4,
	"Might is Right": 9,
	"Mitts": 5,
	"Monochrome": 3,
	"More is Never Enough": 7,
	"No Traces": 9,
	"Nook's Crown": 4,
	"Perfection": 5,
	"Pride Before the Fall": 8,
	"Pride of the First Ones": 7,
	"Prosperity": 10,
	"Rain of Chaos": 8,
	"Rain Tempter": 9,
	"Rats": 8,
	"Rebirth": 27,
	"Remembrance": 8,
	"Sambodhi's Vow": 3,
	"Scholar of the Seas": 7,
	"Seven Years Bad Luck": 13,
	"Shard of Fate": 4,
	"Squandered Prosperity": 5,
	"Struck by Lightning": 3,
	"Succor of the Sinless": 6,
	"The Admirer": 9,
	"The Aesthete": 8,
	"The Archmage's Right Hand": 7,
	"The Arena Champion": 10,
	"The Army of Blood": 6,
	"The Artist": 11,
	"The Avenger": 12,
	"The Bargain": 5,
	"The Battle Born": 5,
	"The Beast": 6,
	"The Betrayal": 9,
	"The Blazing Fire": 6,
	"The Body": 4,
	"The Bones": 6,
	"The Breach": 4,
	"The Brittle Emperor": 8,
	"The Cacophony": 8,
	"The Calling": 6,
	"The Carrion Crow": 4,
	"The Cartographer": 1,
	"The Cataclysm": 13,
	"The Catalyst": 3,
	"The Celestial Justicar": 6,
	"The Celestial Stone": 10,
	"The Chains that Bind": 11,
	"The Chosen": 5,
	"The Coming Storm": 8,
	"The Conduit": 9,
	"The Craving": 4,
	"The Cursed King": 8,
	"The Damned": 6,
	"The Dapper Prodigy": 6,
	"The Dark Mage": 6,
	"The Darkest Dream": 6,
	"The Deal": 5,
	"The Deceiver": 4,
	"The Deep Ones": 5,
	"The Demon": 10,
	"The Demoness": 5,
	"The Doctor": 8,
	"The Doppelganger": 2,
	"The Dragon": 4,
	"The Dragon's Heart": 11,
	"The Dreamer": 6,
	"The Dreamland": 8,
	"The Drunken Aristocrat": 8,
	"The Encroaching Darkness": 8,
	"The Endless Darkness": 9,
	"The Endurance": 4,
	"The Enlightened": 6,
	"The Escape": 5,
	"The Ethereal": 7,
	"The Explorer": 6,
	"The Eye of Terror": 8,
	"The Eye of the Dragon": 10,
	"The Fathomless Depths": 8,
	"The Feast": 5,
	"The Fiend": 11,
	"The Fishmonger": 4,
	"The Fletcher": 5,
	"The Flora's Gift": 5,
	"The Fool": 4,
	"The Formless Sea": 7,
	"The Forsaken": 7,
	"The Fox": 6,
	"The Gambler": 5,
	"The Garish Power": 4,
	"The Gemcutter": 3,
	"The Gentleman": 4,
	"The Gladiator": 5,
	"The Golden Era": 7,
	"The Hale Heart": 4,
	"The Harvester": 11,
	"The Hermit": 9,
	"The Heroic Shot": 1,
	"The Hoarder": 12,
	"The Hunger": 9,
	"The Immortal": 10,
	"The Incantation": 4,
	"The Innocent": 10,
	"The Inoculated": 4,
	"The Insatiable": 3,
	"The Inventor": 6,
	"The Iron Bard": 9,
	"The Jester": 9,
	"The Jeweller's Boon": 5,
	"The Journey": 3,
	"The King's Blade": 5,
	"The King's Heart": 8,
	"The Landing": 5,
	"The Last One Standing": 10,
	"The Lich": 12,
	"The Life Thief": 6,
	"The Lion": 5,
	"The Lord in Black": 6,
	"The Lord of Celebration": 4,
	"The Lover": 2,
	"The Lunaris Priestess": 5,
	"The Mad King": 7,
	"The Master": 4,
	"The Master Artisan": 5,
	"The Mayor": 5,
	"The Mercenary": 5,
	"The Messenger": 4,
	"The Metalsmith's Gift": 6,
	"The Mountain": 6,
	"The Nurse": 8,
	"The Oath": 6,
	"The Obscured": 7,
	"The Offering": 8,
	"The Old Man": 12,
	"The One With All": 6,
	"The Opulent": 5,
	"The Pack Leader": 6,
	"The Pact": 9,
	"The Penitent": 5,
	"The Poet": 9,
	"The Polymath": 3,
	"The Porcupine": 6,
	"The Price of Loyalty": 4,
	"The Primordial": 5,
	"The Professor": 4,
	"The Puzzle": 5,
	"The Queen": 16,
	"The Rabid Rhoa": 4,
	"The Realm": 5,
	"The Risk": 3,
	"The Rite of Elements": 5,
	"The Road to Power": 7,
	"The Ruthless Ceinture": 7,
	"The Sacrifice": 4,
	"The Saint's Treasure": 10,
	"The Samurai's Eye": 3,
	"The Scarred Meadow": 9,
	"The Scavenger": 8,
	"The Scholar": 3,
	"The Seeker": 9,
	"The Sephirot": 11,
	"The Side Quest": 5,
	"The Sigil": 3,
	"The Siren": 7,
	"The Skeleton": 6,
	"The Soul": 9,
	"The Spark and the Flame": 2,
	"The Spoiled Prince": 4,
	"The Standoff": 3,
	"The Stormcaller": 4,
	"The Summoner": 6,
	"The Sun": 7,
	"The Surgeon": 4,
	"The Surveyor": 4,
	"The Survivalist": 3,
	"The Sword King's Salute": 7,
	"The Thaumaturgist": 8,
	"The Throne": 2,
	"The Tower": 6,
	"The Traitor": 4,
	"The Trial": 7,
	"The Twilight Moon": 6,
	"The Twins": 8,
	"The Tyrant": 9,
	"The Undaunted": 5,
	"The Undisputed": 8,
	"The Union": 7,
	"The Valkyrie": 8,
	"The Valley of Steel Boxes": 9,
	"The Vast": 7,
	"The Visionary": 6,
	"The Void": 1,
	"The Warden": 4,
	"The Warlord": 6,
	"The Watcher": 12,
	"The Web": 8,
	"The Wilted Rose": 7,
	"The Wind": 7,
	"The Witch": 8,
	"The Wolf": 5,
	"The Wolf's Legacy": 4,
	"The Wolf's Shadow": 3,
	"The Wolven King's Bite": 8,
	"The Wolverine": 4,
	"The World Eater": 8,
	"The Wrath": 8,
	"The Wretched": 6,
	"Thirst for Knowledge": 5,
	"Three Faces in the Dark": 7,
	"Three Voices": 3,
	"Thunderous Skies": 5,
	"Time-Lost Relic": 10,
	"Tranquillity": 7,
	"Treasure Hunter": 7,
	"Turn the Other Cheek": 3,
	"Underground Forest": 4,
	"Vanity": 9,
	"Vile Power": 5,
	"Vinia's Token": 5,
	"Void of the Elements": 3,
	"Volatile Power": 9,
	"Wealth and Power": 11,
	"Birth of the Three": 3,
	"Dying Anguish": 8,
	"Luck of the Vaal": 1,
	"The Devastator": 8,
	"The Price of Protection": 5,
	"Timeless Eternal Empire Splinter": 100,
	"Timeless Karui Splinter": 100,
	"Timeless Maraketh Splinter": 100,
	"Timeless Templar Splinter": 100,
	"Timeless Vaal Splinter": 100}

SHARDS = {"Scroll Fragment":     "Scroll of Wisdom",
          "Alchemy Shard":       "Orb of Alchemy",
          "Alteration Shard":    "Orb of Alteration",
          "Transmutation Shard": "Orb of Transmutation",
          "Ancient Shard":       "Ancient Orb",
          "Annulment Shard":     "Orb of Annulment",
          "Binding Shard":       "Orb of Binding",
          "Chaos Shard":         "Chaos Orb",
          "Engineer's Shard":    "Engineer's Orb",
          "Exalted Shard":       "Exalted Orb",
          "Harbinger's Shard":   "Harbinger's Orb",
          "Horizon Shard":       "Orb of Horizons",
          "Mirror Shard":        "Mirror of Kalandra",
          "Regal Shard":         "Regal Orb"}

NETS = ["Simple Rope Net",
        "Reinforced Rope Net",
        "Strong Rope Net",
        "Simple Iron Net",
        "Reinforced Iron Net",
        "Strong Iron Net",
        "Simple Steel Net",
        "Reinforced Steel Net",
        "Strong Steel Net",
        "Thaumaturgical Net",
        "Necromancy Net"]

PROPHECIES = [
	"A Master Seeks Help",

	"A Valuable Combination",
	"Fated Connections",
	"Golden Touch",
	"Resistant to Change",
	"Smothering Tendrils",
	"The Beautiful Guide",

	"Cartographer's Chisel",
	"Cartographer's Chisel",
	"The Hardened Armour",
	"Armourer's Scrap",
	"Armourer's Scrap",
	"The Jeweller's Touch",
	"Jeweller's Orb",
	"The Sharpened Blade",
	"Blacksmith's Whetstone",
	"Blacksmith's Whetstone",
	"Touched by the Wind",
	"Orb of Transmutation",
	"Trash to Treasure",
	"Orb of Chance",
	"Twice Enchanted",
	"Vital Transformation",
	"Orb of Transmutation",

	"A Dishonourable Death",
	"A Forest of False Idols",
	"A Rift in Time",
	"A Vision of Ice and Fire",
	"Agony at Dusk",
	"Ancient Doom",
	"Battle Hardened",
	"Black Devotion",
	"Blind Faith",
	"Blinding Light",
	"Burning Dread",
	"Cold Blooded Fury",
	"Cold Greed",
	"Crimson Hues",
	"Dance of Steel",
	"Dark Instincts",
	"Darktongue's Shriek",
	"Dying Cry",
	"End of the Light",
	"Faith Exhumed",
	"Fire and Brimstone",
	"Fire and Ice",
	"From The Void",
	"Greed's Folly",
	"Heavy Blows",
	"Last of the Wildmen",
	"Mouth of Horrors",
	"Nature's Resilience",
	"Pleasure and Pain",
	"Power Magnified",
	"Severed Limbs",
	"Song of the Sekhema",
	"Sun's Punishment",
	"The Apex Predator",
	"The Beginning and the End",
	"The Bishop's Legacy",
	"The Bloody Flowers Redux",
	"The Bowstring's Music",
	"The Dreaded Rhoa",
	"The Fall of an Empire",
	"The Flow of Energy",
	"The Great Leader of the North",
	"The Great Mind of the North",
	"The Karui Rebellion",
	"The King and the Brambles",
	"The King's Path",
	"The Malevolent Witch",
	"The Mentor",
	"The Misunderstood Queen",
	"The Nightmare Awakens",
	"The Queen's Sacrifice",
	"The Servant's Heart",
	"The Silverwood",
	"The Snuffed Flame",
	"The Storm Spire",
	"Trapped in the Tower",
	"Winter's Mournful Melodies",

	"Crushing Squall",
	"Fire from the Sky",
	"Ice from Above",
	"Lightning Falls",
	"The Undead Storm",
	"Vaal Winds",

	"A Call into the Void",
	"A Firm Foothold",
	"A Prodigious Hand",
	"A Whispered Prayer",
	"Abnormal Effulgence",
	"Against the Tide",
	"Baptism by Death",
	"Blood in the Eyes",
	"Blood of the Betrayed",
	"Cleanser of Sins",
	"Custodians of Silence",
	"Fear's Wide Reach",
	"Fire, Wood and Stone",
	"Flesh of the Beast",
	"From Death Springs Life",
	"Graceful Flames",
	"Heart of the Fire",
	"Lost in the Pages",
	"Nemesis of Greed",
	"Notched Flesh",
	"Roth's Legacy",
	"Storm on the Horizon",
	"Storm on the Reef",
	"Strong as a Bull",
	"The Brutal Enforcer",
	"The Eagle's Cry",
	"The Flayed Man",
	"The Hollow Pledge",
	"The Lady in Black",
	"The Last Watch",
	"The Lost Undying",
	"The Mysterious Gift",
	"The Nest",
	"The Petrified",
	"The Prison Guard",
	"The Prison Key",
	"The Queen's Vaults",
	"The Singular Spirit",
	"The Sinner's Stone",
	"The Soulless Beast",
	"The Stockkeeper",
	"The Sword King's Passion",
	"The Vanguard",
	"The Walking Mountain",
	"The Ward's Ward",
	"The Watcher's Watcher",
	"Weeping Death",
	"Wind and Thunder",

	"A Regal Death",
	"Erased from Memory",
	"Lasting Impressions",
	"Overflowing Riches",
	"Pools of Wealth",
	"Reforged Bonds",
	"The Alchemist",
	"The Corrupt",
	"The God of Misfortune",

	"An Unseen Peril",
	"Deadly Twins",
	"Defiled in the Sceptre",
	"Echoes of Witchcraft",
	"Ending the Torment",
	"Fallow At Last",
	"Forceful Exorcism",
	"Hidden Reinforcements",
	"Hidden Vaal Pathways",
	"Holding the Bridge",
	"In the Grasp of Corruption",
	"Living Fires",
	"Monstrous Treasure",
	"Mysterious Invaders",
	"Path of Betrayal",
	"Plague of Frogs",
	"Plague of Rats",
	"Possessed Foe",
	"Rebirth",
	"Risen Blood",
	"Soil, Worms and Blood",
	"The Brothers of Necromancy",
	"The Child of Lunaris",
	"The Cursed Choir",
	"The Forgotten Garrison",
	"The Forgotten Soldiers",
	"The Four Feral Exiles",
	"The Hungering Swarm",
	"The Invader",
	"The Trembling Earth",
	"The Twins",
	"The Undead Brutes",
	"Undead Uprising",
	"Unnatural Energy",
	"Vaal Invasion",
	"Visions of the Drowned",
	"Waiting in Ambush",

	"Bountiful Traps",
	"Erasmus' Gift",
	"Gilded Within",
	"Hunter's Lesson",
	"Kalandra's Craft",
	"The Dream Trial",
	"The Dreamer's Dream",
	"The Fortune Teller's Collection",
	"The Lost Maps",
	"The Scout",
	"The Wealthy Exile",

	"Anarchy's End I",
	"Anarchy's End II",
	"Anarchy's End III",
	"Anarchy's End IV",
	"Ancient Rivalries I",
	"Ancient Rivalries II",
	"Ancient Rivalries III",
	"Ancient Rivalries IV",
	"Beyond Sight I",
	"Beyond Sight II",
	"Beyond Sight III",
	"Beyond Sight IV",
	"Day of Sacrifice I",
	"Day of Sacrifice II",
	"Day of Sacrifice III",
	"Day of Sacrifice IV",
	"Deadly Rivalry I",
	"Deadly Rivalry II",
	"Deadly Rivalry III",
	"Deadly Rivalry IV",
	"Deadly Rivalry V",
	"The Feral Lord I",
	"The Feral Lord II",
	"The Feral Lord III",
	"The Feral Lord IV",
	"The Feral Lord V",
	"The Plaguemaw I",
	"The Plaguemaw II",
	"The Plaguemaw III",
	"The Plaguemaw IV",
	"The Plaguemaw V",
	"Thaumaturgical History I",
	"Thaumaturgical History II",
	"Thaumaturgical History III",
	"Thaumaturgical History IV",
	"The Ambitious Bandit I",
	"The Ambitious Bandit II",
	"The Ambitious Bandit III",
	"Unbearable Whispers I",
	"Unbearable Whispers II",
	"Unbearable Whispers III",
	"Unbearable Whispers IV",
	"Unbearable Whispers V",
	"The Unbreathing Queen I",
	"The Unbreathing Queen II",
	"The Unbreathing Queen III",
	"The Unbreathing Queen IV",
	"The Unbreathing Queen V",
	"The Warmongers I",
	"The Warmongers II",
	"The Warmongers III",
	"The Warmongers IV"]

PROPHECY_CHAINS = {
	"Anarchy's End": 4,
	"Ancient Rivalries": 4,
	"Beyond Sight": 4,
	"Day of Sacrifice": 4,
	"Deadly Rivalry": 5,
	"The Feral Lord": 5,
	"The Plaguemaw": 5,
	"Thaumaturgical History": 4,
	"The Ambitious Bandit": 3,
	"Unbearable Whispers": 5,
	"The Unbreathing Queen": 5,
	"The Warmongers": 4}

DISCONTINUED_PROPHECIES = [
	"Ancient Rivalries I",
	"Ancient Rivalries II",
	"Ancient Rivalries III",
	"Ancient Rivalries IV",
	"A Gracious Master",
	"The Aesthete's Spirit",
	"Brothers in Arms",
	"Echoes of Mutation",
	"Echoes of Lost Love",
	"The Emperor's Trove",
	"The Blacksmith"]

DISCONTINUED_PROPHECY_CHAINS = {
	"Ancient Rivalries": 4}

def getStackSize(item):
	if item not in STACK_SIZES:
		return 1
	return STACK_SIZES[item]
